backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Նորություններ"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Վերնագիր", name: "title", widget: "string" }
      - { label: "Ամսաթիվ", name: "date", widget: "datetime" }
      - { label: "Տեքստ", name: "body", widget: "markdown" }
